# Generated by Django 5.1.7 on 2025-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_registro_delete_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
